version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '4200:4200'
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
