apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb-express
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      # nodePort: 30002 # Define the local MongoDB port.
  type: ClusterIP
