apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express # The name of the Deployment.
spec:
  selector:
    matchLabels:
      app: mongodb-express # Run MongoDB Express.
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongodb-express
          image: mongo-express # Use the MongoDB Express image.
          resources:
            limits:
              # Memory.
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            # Set login and password with environment variables.
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb-service
