apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express # The name of the Deployment.
  namespace: mongodb-express
spec:
  selector:
    matchLabels:
      app: mongodb-express # Run MongoDB Express.
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongodb-express
          # image: mongo-express:0.54.0 # Use the MongoDB Express image.
          image: mongo-express:1.0.0-alpha.4
          # image: mongo-express:latest
          # image: mongo-express
          # image: mongo-express:1.1.0-rc-3
          resources:
            limits:
              # Memory.
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_AUTH_DATABASE
              value: "admin"
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN 
              value: "true"
            # Set login and password with environment variables.
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb-service.mongodb-express.svc.cluster.local
