apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-express-configmap
  namespace: mongodb-express
data:
  database_url: mongodb-service # Use the `MongoDB` service to define the database for the Deployment.
